### ISSUE TITLE
Status on different instance

### ISSUE THREAD

**Issue by JBGruber** [schochastics/rtoot#11]
I get:

``` r
library("rtoot")
get_status(id = "109297677620300632")
#> Error in make_get_request(token = token, path = path, params = list()): something went wrong. Status code: 404
```

The problem is that the request URL is automatically set from my token ("https://fosstodon.org/api/v1/statuses/109298295023649405"), yet this status was posted on a different instance. There is currently no way to change the instance of the status. This works, by the way :smile: :

```
token2 <- token
token2$instance <- "mastodon.social"
get_status(id = "109297677620300632", token = token2)
```

**Comment by schochastics** [comment]
hmm any suggestions? would it be an option to have an optional instance parameter? if it is NULL use the one from the token, else use that instance?

**Comment by chainsawriot** [comment]
One way to deal with this is add an `instance` parameter to all functions to bypass the `$instance` stored in the token.

**Comment by schochastics** [comment]
that's what I thought too. But probably only makes sense for the public endpoints (see https://github.com/schochastics/rtoot/issues/12#issuecomment-1305204606)

**Comment by JBGruber** [comment]
This is exactly what I would have suggested and it works well. When bypassing the checks in `make_get_request`, however, it also works without a token. So I agree it would make sense to let users lookup statuses without authentication.

**Comment by schochastics** [comment]
this should be fixed now
