### ISSUE TITLE
Not exporting `print.rtoot_client`

### ISSUE THREAD

**Issue by chainsawriot** [schochastics/rtoot#112]
https://github.com/schochastics/rtoot/blob/5821642244d09dbb755bd6557eed7cdccb15be4f/R/utils.R#L2-L5

Should it still be exported?

There is no normal way for a user to create (and see) a client object, except maybe: `rtoot:::get_client()`.

**Comment by schochastics** [comment]
hmm probably don't need it anymore. I can quickly "unexport" it
