### ISSUE TITLE
Not everything needs a token

### ISSUE THREAD

**Issue by schochastics** [schochastics/rtoot#12]
Some endpoints can be used [anonymously](https://docs.joinmastodon.org/client/public/). Shouldn't force the use of tokens everywhere
 
(Also related to #11)

**Comment by schochastics** [comment]
Endpoints:

## anonymous requests (https://docs.joinmastodon.org/client/public/)

- [GET /api/v1/accounts/:id](https://docs.joinmastodon.org/methods/accounts/)
- [GET /api/v1/accounts/:id/statuses](https://docs.joinmastodon.org/methods/statuses/) 
- [GET /api/v1/statuses/:id](https://docs.joinmastodon.org/methods/statuses/#view-specific-status)
- [GET /api/v1/statuses/:id/reblogged_by](https://docs.joinmastodon.org/methods/statuses/#boosted-by) 
- [GET /api/v1/statuses/:id/favourited_by](https://docs.joinmastodon.org/methods/statuses/#favourited-by)
- [GET /api/v1/statuses/:id/context](https://docs.joinmastodon.org/methods/statuses/#parent-and-child-statuses) 
- [GET /api/v1/polls/:id](https://docs.joinmastodon.org/methods/statuses/polls/) 

- [GET /api/v1/instance](https://docs.joinmastodon.org/methods/instance/#fetch-instance)
- [GET /api/v1/instance/peers](https://docs.joinmastodon.org/methods/instance/#list-of-connected-domains)
- [GET /api/v1/instance/activity](https://docs.joinmastodon.org/methods/instance/#weekly-activity)
- [GET /api/v1/custom_emojis](https://docs.joinmastodon.org/methods/instance/custom_emojis/#custom-emoji).
- [GET /api/v1/directory](https://docs.joinmastodon.org/methods/instance/directory/#view-profile-directory) 
- [GET /api/v1/trends](https://docs.joinmastodon.org/methods/instance/trends/#trending-tags)

Some instances might require auth for some of these endpoints

## client (https://docs.joinmastodon.org/client/token/#creating-our-application)

- [GET /api/v1/accounts/:id/following](https://docs.joinmastodon.org/methods/accounts/#following)
- [GET /api/v1/accounts/:id/followers](https://docs.joinmastodon.org/methods/accounts/#followers)

## user (https://docs.joinmastodon.org/client/authorized/)

- [POST /api/v1/statuses](https://docs.joinmastodon.org/methods/statuses/#publish-new-status) 
- [/api/v1/media](https://docs.joinmastodon.org/methods/statuses/media/) 
- [/api/v1/scheduled_statuses](https://docs.joinmastodon.org/methods/statuses/scheduled_statuses/) 

Some of the public endpoints have actions that require user auth

**Comment by JBGruber** [comment]
As far as I can see, you only need to change:

```
make_get_request <- function(token, path, params, instance = NULL, anonymous = FALSE, ...) {

  if (is.null(instance) && anonymous) {
    stop("provide either an instance or a token")
  }

  if (is.null(instance)) {
    token <- check_token_rtoot(token)
    url <- prepare_url(token$instance)
    config <- httr::add_headers(Authorization = paste('Bearer', token$bearer))
  } else {
    url <- prepare_url(instance)
    config = list()
  }

  request_results <- httr::GET(httr::modify_url(url, path = path),
                               config,
                               query = params)

  status_code <- httr::status_code(request_results)
  if (!status_code %in% c(200)) {
    stop(paste("something went wrong. Status code:", status_code))
  }
  return(httr::content(request_results))
}
```
Then every function that wraps an endpoint that takes anyonymous requests can do something like this:

```
get_status <- function(id, token = NULL, instance = NULL, anonymous = FALSE) {
  if (!anonymous) token <- check_token_rtoot(token)
  path <- paste0("/api/v1/statuses/", id)
  make_get_request(token = token, path = path, params = list(), anonymous = anonymous)
}
```

**Comment by schochastics** [comment]
yes this should do the trick. Working on it :)
