### ISSUE TITLE
Add Notification Access

### ISSUE THREAD

**Issue by pbulsink** [schochastics/rtoot#121]
It would be convenient to have API access to notifications, either by streaming (https://docs.joinmastodon.org/methods/streaming/#notification) or directly (https://docs.joinmastodon.org/methods/notifications/). This would simplify the creation of interactive applications (i.e. responding to a mentioning status, interacting with users who favourite/reblog, etc.).

**Comment by schochastics** [comment]
@pbulsink: The return is a bit more complicated then the standard API output. But if you need it right now, you can use an unexported function:
`rtoot:::make_get_request(path="/api/v1/notifications",token=NULL)`

**Comment by chainsawriot** [comment]
#34

**Comment by schochastics** [comment]
with the new generic function:
`rtoot(endpoint = "api/v1/notifications")`

**Comment by schochastics** [comment]
Not going to add this due to complex return structure. If needed, please use the generic ` rtoot(endpoint = "api/v1/notifications")`
