### ISSUE TITLE
extend verify credentials to clients

### ISSUE THREAD

**Issue by schochastics** [schochastics/rtoot#13]
currently only user tokens can be verified. Clients can be verified too: https://docs.joinmastodon.org/client/token/

**Comment by schochastics** [comment]
@JBGruber maybe the reason some of your verification failed is that the verifying credentials for users and clients calls different endpoints? The commit above fixes that

**Comment by JBGruber** [comment]
Yes, that was the problem! It didn't occur to me that the endpoints are different.
