### ISSUE TITLE
Adding users to lists?

### ISSUE THREAD

**Issue by smach** [schochastics/rtoot#135]
Thank you for this package! It would be awesome if we could add users to lists with rtoot. Managing lists is still one by one in the Web interface and clients. If you want to bulk import someone else's followers to a list, or move instances and re-create your existing lists on a new server, it's very cumbersome now (as I’m discovering as I try to move instances). I see the endpoint argument option only supports GET currently.

**Comment by schochastics** [comment]
@smach implemented now via `post_list_accounts()`. Problem is that you need the account ids, which you need to get via your follower list.
