### ISSUE TITLE
save token to environment

### ISSUE THREAD

**Issue by schochastics** [schochastics/rtoot#18]
See discussion https://github.com/schochastics/rtoot/pull/15#issuecomment-1305331944

**Comment by JBGruber** [comment]
Not sure if it makes more sense to save the token or the token location as the env variable. The token consists of 3 relevant parts: bearer, instance and type. These could go into one env variable, but we would need to also parse it then. Or they go into 3 variables, which seems a bit clumsy to me. 

I would say the file and path in the variable approach is cleaner. But maybe we need the whole token for testing (#19)?

**Comment by chainsawriot** [comment]
@JBGruber Not in a straight sense. The envvar `RTOOT_DEFAULT_TOKEN` is for filtering out the sensitive information (i.e. the token) when creating vcr cassettes. It won't need for testing.

**Comment by chainsawriot** [comment]
GOTO #68
