### ISSUE TITLE
dplyr dependency needed?

### ISSUE THREAD

**Issue by schochastics** [schochastics/rtoot#21]
Very convenient here: https://github.com/schochastics/rtoot/blob/main/R/instances.R#L75
If we do not need more functionality from `dplyr`, we could try to recreate this in base

**Comment by chainsawriot** [comment]
It sounds okay to me. `dplyr`'s dependencies overlap a great deal with `tibble` and `httr`.

**Comment by schochastics** [comment]
leaving it for now then
