### ISSUE TITLE
Endpoints to cover

### ISSUE THREAD

**Issue by schochastics** [schochastics/rtoot#27]
Endpoints (probably not complete list) to add to rtoot

- [x] [GET /api/v1/accounts/:id](https://docs.joinmastodon.org/methods/accounts/)
- [x]  GET /api/v1/accounts/search
- [x] [GET /api/v1/accounts/:id/statuses](https://docs.joinmastodon.org/methods/statuses/) 
- [x] [GET /api/v1/statuses/:id](https://docs.joinmastodon.org/methods/statuses/#view-specific-status)
- [x] [GET /api/v1/statuses/:id/reblogged_by](https://docs.joinmastodon.org/methods/statuses/#boosted-by) @chainsawriot 
- [x] [GET /api/v1/statuses/:id/favourited_by](https://docs.joinmastodon.org/methods/statuses/#favourited-by) @chainsawriot 
- [x] [GET /api/v1/statuses/:id/context](https://docs.joinmastodon.org/methods/statuses/#parent-and-child-statuses) @chainsawriot 
- [x] [GET /api/v1/polls/:id](https://docs.joinmastodon.org/methods/statuses/polls/) @chainsawriot 
- [x] [GET /api/v1/timelines/tag/:hashtag](https://docs.joinmastodon.org/methods/timelines/#hashtag-timeline) @chainsawriot 
- [x] GET /api/v1/timelines/public @chainsawriot 
- [x] GET /api/v1/timelines/home @chainsawriot 
- [x] GET /timelines/list/:list_id @chainsawriot 
- [x] [GET /api/v1/instance](https://docs.joinmastodon.org/methods/instance/#fetch-instance) 
- [x] [GET /api/v1/instance/peers](https://docs.joinmastodon.org/methods/instance/#list-of-connected-domains) 
- [x] [GET /api/v1/instance/activity](https://docs.joinmastodon.org/methods/instance/#weekly-activity)
- [x] [GET /api/v1/custom_emojis](https://docs.joinmastodon.org/methods/instance/custom_emojis/#custom-emoji) 
- [x] [GET /api/v1/directory](https://docs.joinmastodon.org/methods/instance/directory/#view-profile-directory) 
- [x] [GET /api/v1/trends](https://docs.joinmastodon.org/methods/instance/trends/#trending-tags) 

- [x] [GET /api/v1/accounts/:id/following](https://docs.joinmastodon.org/methods/accounts/#following) @schochastics 
- [x] [GET /api/v1/accounts/:id/followers](https://docs.joinmastodon.org/methods/accounts/#followers) @schochastics 
- [x] GET /api/v1/accounts/:id/featured_tags @schochastics
- [x] GET /api/v1/accounts/:id/lists @schochastics 
- [x] GET /api/v1/accounts/relationships @schochastics 

- [x] GET /api/v1/bookmarks
- [x] GET /api/v1/favourites
- [x] GET/api/v1/mutes
- [x] GET /api/v1/blocks

- [x] [POST /api/v1/statuses](https://docs.joinmastodon.org/methods/statuses/#publish-new-status) 
- [x] [/api/v1/media](https://docs.joinmastodon.org/methods/statuses/media/) 
- [x] [/api/v1/scheduled_statuses](https://docs.joinmastodon.org/methods/statuses/scheduled_statuses/) 
- [x]  POST /api/v1/accounts/:id/(un)follow
- [x]  POST /api/v1/accounts/:id/(un)block
- [x]  POST /api/v1/accounts/:id/(un)mute
- [x]  POST /api/v1/accounts/:id/(un)pin
- [x] POST /api/v1/accounts/:id/note

(please add comment if you find more)

**Comment by chainsawriot** [comment]
- [ ]  `/api/v1/accounts/:id/statuses` I am on it. Make it compatible with `rtweet`, it's gonna called `get_timeline`.

**Comment by schochastics** [comment]
ah sorry just pushed something for that but please feel free to delete and use get_timeline, which makes more sense!

**Comment by schochastics** [comment]
hmm but on another thought, do we want to mask rtweet functions?

**Comment by chainsawriot** [comment]
@schochastics No worries. Then I switch to something else. Maybe I should focus on [timelines](https://docs.joinmastodon.org/methods/timelines/) (hashtag timeline etc.).

**Comment by chainsawriot** [comment]
@schochastics Good point! We shouldn't.

**Comment by schochastics** [comment]
@chainsawriot ok then I leave it as is for now. Maybe we need to rename things later. You can focus on timelines, I check out some more user related stuff

**Comment by schochastics** [comment]
there are still more user level endpoints, but we can "save" them for later

**Comment by chainsawriot** [comment]
I can also handle the rest of two. The poll one is pretty straightforward. The context one is a bit tricky. For `parse`, we might need to return a list of two tibbles (of statuses).

**Comment by schochastics** [comment]
yes I leave them for you.
