### ISSUE TITLE
save a default instance

### ISSUE THREAD

**Issue by schochastics** [schochastics/rtoot#3]
Users shouldn't constantly have to supply the mastodon instance

**Comment by chainsawriot** [comment]
#2

**Comment by schochastics** [comment]
mind reading

**Comment by chainsawriot** [comment]
I was thinking about organizing the whole thing as an R6, because it is more like a typical DB client rather than something like `rtweet` or `academictwitteR` (which has only one URL). But that would also introduce a lot of complexity for development.

**Comment by schochastics** [comment]
I am still working through the API docs to get a full understanding. Learning R6 has been on my TODO list for a while so maybe we can have this on the roadmap for later if refactoring wouldn't be too complex
