### ISSUE TITLE
enable login 

### ISSUE THREAD

**Issue by schochastics** [schochastics/rtoot#4]
either `create_bearer()` should allow to login a user or there should be a separate function

**Comment by schochastics** [comment]
@chainsawriot any experience with handling authentication? Do you think my solution is ok?

**Comment by schochastics** [comment]
auth works: https://mastodon.social/@schochastics/109297677620300632

**Comment by chainsawriot** [comment]
@schochastics It's possible to do it with [oauth2.0_token()](https://httr.r-lib.org/reference/oauth2.0_token.html) also.

**Comment by schochastics** [comment]
I will give it a shot later. If I fail, you may fix that ;-)

**Comment by chainsawriot** [comment]
@schochastics I am experimenting with it. It is quite tedious.
