### ISSUE TITLE
Enable pagination by returning max_id and since_id

### ISSUE THREAD

**Issue by noamross** [schochastics/rtoot#41]
List of statuses and followers take `max_id` and `since_id` in order to fetch paginated results, but the values for these are not returned with the results.  They are available in the `link` header of the HTTP response.  I suggest, as a first pass, that these values be returned as attributes of the return object, parsed or not.

In the longer term, including a pagination option to automatically loop through results to a `paginated_limit` would be good, provided it includes a provision for respecting rate limits.

Great work on this package!

**Comment by chainsawriot** [comment]
An interim solution

https://github.com/schochastics/rtoot/wiki/Pagination

**Comment by noamross** [comment]
Thanks.  That works for statuses. However the `max_id` and `next_id` values for non-status endpoints (e.g.  follower and following endpoints), are internal values that don't match up with the ID values of users (and I suspect blocks and other paginated values).

**Comment by schochastics** [comment]
Good point. But we definitely need a way of rate limit checking before. I assume this will be a bit more complex so we might move this till after the first release

**Comment by noamross** [comment]
Agreed, but I think exposing the max/since IDs would be good for a first release.

**Comment by schochastics** [comment]
Good point, so users can do their own pagination for now

**Comment by schochastics** [comment]
@chainsawriot I will take a look at this while refactoring redundant code

**Comment by schochastics** [comment]
I implemented a parser for the header
```r
# process the header of a get request
parse_header <- function(header){
  # rate limit fields should always be present but the link field is not always there
  df <- tibble::tibble(rate_limit=header[["x-ratelimit-limit"]],
                       rate_remaining=header[["x-ratelimit-remaining"]],
                       rate_reset=format_date(header[["x-ratelimit-reset"]]))
  if("link"%in%names(header)){
    link <- header[["link"]]
    #extract all variables from link to a list TODO: check if others are relevant
    vars_to_search <- "max_id|min_id|since_id"
    reg <- paste0("(",vars_to_search,")=[0-9]+")
    param_extract <- regmatches(link, gregexpr(reg, link))[[1]]
    param_names <- regmatches(param_extract, gregexpr(vars_to_search, param_extract))
    names(param_extract) <- param_names
    param_extract <- gsub(".*?([0-9]+).*", "\\1", param_extract)
    page_param <- tibble::as_tibble(as.list(param_extract))
    return(dplyr::bind_cols(df,page_param))
  } else{
    return(df)
  }
}
```

I ran some tests and it seems stable. The function returns a tibble with rate limits and paging  parameters. I'll attach this as a attr to the output rahter than the whole header

**Comment by chainsawriot** [comment]
If there is a good way to grab the urls, Maybe we can just use `httr::parse_url`.

```r
httr::parse_url("https://social.tchncs.de/api/v1/timelines/public?limit=20&local=FALSE&max_id=109309995641782179&only_media=FALSE&remote=FALSE")$query$max_id
```

**Comment by schochastics** [comment]
that'll be much easier than that regex nightmare of mine :D. I check

**Comment by schochastics** [comment]
```r
header$link
#>"<https://fosstodon.org/api/v1/accounts/109302436954721982/followers?limit=40&max_id=1011856>; rel=\"next\", <https://fosstodon.org/api/v1/accounts/109302436954721982/followers?limit=40&since_id=1076460>; rel=\"prev\""
httr::parse_url(header$link)$query$max_id
#> [1] "1011856>; rel=\"next\", <https://fosstodon.org/api/v1/accounts/109302436954721982/followers?limit=40"
```
would still need some regex magic I am afraid

**Comment by chainsawriot** [comment]
So used to `stringr` and I need to find a way to do that with base.

```r
stringr::str_extract_all(header[["link"]], "https[^>]+")[[1]]
```

**Comment by schochastics** [comment]
jep I am scratching my head over that right now

**Comment by chainsawriot** [comment]
From [stackoverflow](https://stackoverflow.com/questions/64740433/base-r-equivalent-of-stringrstr-extract-all)

```r
regmatches(header[["link"]], gregexpr("https[^>]+", header[["link"]]))[[1]]
```

**Comment by schochastics** [comment]
```r
# process the header of a get request
parse_header <- function(header){
  # rate limit fields should always be present but the link field is not always there
  df <- tibble::tibble(rate_limit=header[["x-ratelimit-limit"]],
                       rate_remaining=header[["x-ratelimit-remaining"]],
                       rate_reset=format_date(header[["x-ratelimit-reset"]]))
  if("link"%in%names(header)){
    vars_to_search <- c("max_id","min_id","since_id")
    links <- regmatches(header[["link"]], gregexpr("https[^>]+", header[["link"]]))[[1]]
    query_params <- lapply(links,function(x){
      query <- httr::parse_url(x)[["query"]]
      query <- query[names(query)%in%vars_to_search]
    })
    page_param <- dplyr::bind_cols(query_params)

    return(dplyr::bind_cols(df,page_param))
  } else{
    return(df)
  }
}
```
looks better I think?

**Comment by schochastics** [comment]
@noamross You should now be able to do your own pagination: https://github.com/schochastics/rtoot/wiki/Pagination#followers
