### ISSUE TITLE
Parse output from `get_instance_directory`

### ISSUE THREAD

**Issue by chainsawriot** [schochastics/rtoot#55]
https://github.com/schochastics/rtoot/blob/5ab763d9caa6a99a7dea313c5f5c795718e2a97a/R/instances.R#L84

I think it makes more sense now to use `process_request` with `FUN` being `v(parse_account)`.

I can bake that also in #54

**Comment by schochastics** [comment]
yes please bake that into #54

**Comment by chainsawriot** [comment]
@schochastics Done!
