### ISSUE TITLE
Make `get_fedi_instances` testable with `vcr`

### ISSUE THREAD

**Issue by chainsawriot** [schochastics/rtoot#56]
https://github.com/schochastics/rtoot/blob/5ab763d9caa6a99a7dea313c5f5c795718e2a97a/R/instances.R#L11

This is not testable with `vcr`. A easy fix is to use `httr::GET` instead.

Can also bake into #54

**Comment by schochastics** [comment]
yes please bake that into #54

**Comment by chainsawriot** [comment]
@schochastics Done too!
