### ISSUE TITLE
rename timeline functions

### ISSUE THREAD

**Issue by schochastics** [schochastics/rtoot#57]
At the moment we have `get_home_timeline()`, `get_public_timeline()`, `get_list_timeline()`, and `get_hashtag_timeline()`.
Should we rename those to
`get_timeline_home()`,`get_timeline_public()`,`get_timeline_list()`, and `get_timeline_hashtag()`

would be better for autocomplete in RStudio and more consistent with the get_account functions.

@chainsawriot what do you think? How much would that mess up testing? would a simple search and replace suffice to fix this?
I'd do that if there are no complex issues

**Comment by chainsawriot** [comment]
I think the renaming makes sense. It is better to do it now than after the
official release.

About testing, we probably need to rename the cassette files (test cases)
in the fixtures directory.

**Comment by schochastics** [comment]
Ok let me give it a shot. I also suspect that it is only a case of renaming the files.
