### ISSUE TITLE
re: get_context( ) function

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [schochastics/rtoot#65]
Hello rtoot !

I have been reading the documentation and trying out the functions. I have some issues on the function `post_context()`.

1. My main issue is the name of this function, it _should_ be called `post_replies` or 'toot_replies` as that is what it returns, as "context" to me meant there was some sentiment analysis or something going on. Only after testing this with a post and seeing that what gets returned is the replies to  a user's post. 
2.  issue with the id required _should_ be named **post_id** as to be very clear what `id` is needed as `id` is used in every function in this package and there is a difference between `user_id` and `post_id`
3. when I save the function into a variable and try to retrieve the content i get errors,  I tried to use a tidyverse method of selecting the `descendants` and unlist them. The only way to get the content is to use the `$`, `post_context$descendants$content`

anyway, thanks for this nice package, i have been enjoying it.  😄 

<img height='400' src='https://user-images.githubusercontent.com/55933131/201434601-5508b4b9-91de-43e3-b442-9beadf2c9a1c.png'>

**Comment by schochastics** [comment]
I think we definitely have to rethink the `id` parameter because it means different things in different functions. Re naming, I wouldnt want to change it because context is the official API name and you also get the predecessor posts, so replies doesnt capture that but context does

**Comment by PythonCoderUnicorn** [comment]
okay, I just wanted to share my thoughts. I save these functions with names that I find most accurate and helpful. 

as for item 3, I still don't understand why the results are nested lists. Not a big issue, i will just move on regarding it.

**Comment by schochastics** [comment]
No worries, that was a valid concern :). Regarding 3, we will think about a different structure but i think given that atencedents and descendants are two different sets of post, it makes sense to separate them somehow
