### ISSUE TITLE
re: content cleaning of strings

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [schochastics/rtoot#67]
Hi rtoot !

I am running into some string cleaning issues with 3 of the functions: `get_account_bookmarks()`, `get_account_favourites()` 
and `get_account_statuses(user_id= )`. I am posting to inform you as it could be just my issue, but in case it's not.

Goal: clean content text using `stringr` to remove the HTML tags and punctuation. 

here is what I have tried using but I keep getting text with the `<p>` tags and/or the `<span>` tag. 

 account bookmarks
```
bookmarks = rtoot::get_account_bookmarks()
bookmarks %>% 
  select( content) %>% 
  mutate(text = str_remove_all(content, "[:graph:]"),
         text = str_remove_all(content, "[:punct:]"),
         text = str_remove_all(content, "<span>"),
         text = str_remove_all(content, "<p>"),
         text = str_remove_all(content, "<p><span class="),
         text = str_remove_all(content, "h-card\\>"),
         text = str_remove_all(content, "<a href")  
  ) %>%
  select(text)
```

favorites

```
faves = rtoot::get_account_favourites() 
faves %>% 
  select(id, content) %>% 
  mutate(text = str_remove_all(content, "[:graph:]"),
         text = str_remove_all(content, "[:punct:]"),
         text = str_remove_all(content, "<span>"),
         text = str_remove_all(content, "<p>"),
         text = str_remove_all(content, "</p>"),
         text = str_remove_all(content, "<p><span class="),
         text = str_remove_all(content, "h-card\\>"),
         text = str_remove_all(content, "<a href")     
  ) %>%
  select(content)
```

account statuses
```
posts = rtoot::get_account_statuses(id = alison_id)
posts %>% 
  select(content) %>% 
  mutate(clean = str_remove_all(content, "[:punct:]" ),
         clean = str_remove_all(content, "<p>" ),
         clean = str_remove_all(content, "href" ),
  ) %>% 
  select(clean)
```

### the output 

bookmarks
<img width="800" alt="Screen Shot 2022-11-11 at 3 27 11 PM" src="https://user-images.githubusercontent.com/55933131/201439386-772390ee-52e7-4c53-ab7e-b31525ac6fea.png">

account favorites
<img width="800" alt="Screen Shot 2022-11-11 at 3 28 21 PM" src="https://user-images.githubusercontent.com/55933131/201439482-94b3dd73-334b-4fb8-8372-894af6ab9e36.png">

account statuses
<img width="800" alt="Screen Shot 2022-11-11 at 3 29 09 PM" src="https://user-images.githubusercontent.com/55933131/201439566-d374502c-d32c-4b8a-a245-2ad66e0c2e82.png">

---
So as you can see, I did try to clean the text which works fine on other functions such as `get_status()` and `get_timeline_hashtag()`.  Just letting you know about it, maybe there is something I am missing here on cleaning the text. Maybe in the future there could be a function like in `rvest::html_text2()` which strips away the html. 

Anyway, thanks for the package 😺

**Comment by chainsawriot** [comment]
https://github.com/schochastics/rtoot/wiki/html

**Comment by PythonCoderUnicorn** [comment]
thanks !

I did initially try to use the `rvest::html_text2()` function but got an error, seems like i was on the right path, just need to map over it. Glad to know that my idea wasn't wrong.

**Comment by schochastics** [comment]
I think we will need to add a way of automatically clean the text or at least provide a function to do so

**Comment by schochastics** [comment]
After giving it some thought, we will not add such a function. This would require to add rvest as a dependency and that is not justified given that we only need one function from it. The solution will remain accessible in the [wiki](https://github.com/schochastics/rtoot/wiki/html)
