### ISSUE TITLE
Token as environment variable

### ISSUE THREAD

**Issue by mattkerlogue** [schochastics/rtoot#68]
First off, huge thanks and massive congratulations for getting the rtoot package off the ground! :tada:

It's meant that I've been able to port my [Twitter bot](https://github.com/mattkerlogue/narrowbotR/) over to the botsin.space instance.

Related to #7 and #18. I've had to adopt a different approach to authentication as it runs on GitHub Actions, therefore I can't make use of an RDS hidden away deep in the system to store the token.

The approach used in `{rtweet}` is to use environment variables and within the project I've implemented what appears to be a [working solution](https://github.com/mattkerlogue/narrowbotR/blob/main/R/mastodon_token.R) that mimics this approach with `{rtoot}`. The workflow is as follows:

- A new function `mastodon_token()` which creates the same underlying list structure as `auth_setup()` but to which you provide the access token, type and instance. I couldn't see an internal function that did this, but let me know if there is. This relies on the user generating their own key/token from within the Mastodon API settings, but it's pretty simple for folk that would want to get this complicated (and definitely easier than the approach with the Twitter API).

- User writes their token to an .Renviron file, either at the user-level or project-level:
```r
MASTODON_TOKEN="yoUrM4sToD0nt0k3N"
```

- User then includes the following in their code:
```r
# to use the defaults
toot_token <- mastodon_token()

# or to be explicit
toot_token <- mastodon_token(
  access_token = Sys.getenv("MASTODON_TOKEN"),
  type = "user",
  instance = "botsin.space"
)

rtoot::post_toot(
  status = status_msg,
  media = tmp_file,
  alt_text = alt_msg,
  token = toot_token
)
```

I discuss in more length in [this blog post](https://lapsedgeographer.london/2022-11/mastodon-switch/) about migrating the bot to Mastodon.

Happy to contribute a PR if you'd like to include in rtoot's core functionality, but probably worth some consideration of how it interacts with the existing approach to authentication.

**Comment by schochastics** [comment]
Bots are an obvious use case for the environment approach to tokens (Haven't thought of that yet) so we need to address this somehow. However, I am also with @JBGruber (see https://github.com/schochastics/rtoot/issues/18#issuecomment-1307656941)  that it is a bit clumsy to write 3 (well technically only 2 are needed) variables as system variables. I'd prefer a solution that allows both RDS and ENV. Like: "if ENV not found, look for RDS". RDS is more accessible in my opinion than telling users to create 2 system variables.   @chainsawriot thoughts? @JBGruber you wrote the auth part, any suggestions from your side?

**Comment by chainsawriot** [comment]
@mattkerlogue Thanks for the suggestion. As you might know, we have used different names for testing. But I think that can be easily harmonized.

https://github.com/schochastics/rtoot/blob/a24b44de80f0da182c17f0e8cd753bef21c3e216/tests/testthat/setup-rtoot.R#L4-L6

@schochastics I have another solution actually. One envvar.

``` r
require(rtoot)
#> Loading required package: rtoot
Sys.setenv(RTOOT_DEFAULT_TOKEN="aslfjkhdjkfhskjlafhsadf;public;emacs.ch")
get_token_from_envvar <- function(envvar = "RTOOT_DEFAULT_TOKEN") {
    if (Sys.getenv(envvar) == "") {
        stop("envvar not found.")
    }
    res <- strsplit(x = Sys.getenv(envvar), split = ";")[[1]]
    bearer <- list(bearer = res[1])
    bearer$type <- res[2]
    bearer$instance <- res[3]
    class(bearer) <- "rtoot_bearer"
    bearer
}

get_token_from_envvar("whatever")
#> Error in get_token_from_envvar("whatever"): envvar not found.
get_token_from_envvar("RTOOT_DEFAULT_TOKEN")
#> <mastodon bearer token> for instance: emacs.ch of type: public
```

<sup>Created on 2022-11-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by JBGruber** [comment]
I thought about something in the same lines as @chainsawriot. One token that is parsed to make the list object.

I think it would make sense to keep the option and add a condition to parse the environment variable if `options("rtoot_token" = "environment")`.

**Comment by schochastics** [comment]
Sounds good to me. @chainsawriot do you want to implement this?

**Comment by chainsawriot** [comment]
@mattkerlogue You can now convert your token

```r
x <- convert_token_to_envvar(token)
```
