### ISSUE TITLE
Package-level documentation

### ISSUE THREAD

**Issue by AmeliaMN** [schochastics/rtoot#89]
I like being able to use `?` to jump into the documentation for a package, e.g.

```
?rtoot
```

This requires a field in the roxygen, I believe `"_PACKAGE"`. (See https://github.com/rstudio/tinytex/issues/361 for Yihui's explanation when I asked for this on `tinytex`).

**Comment by schochastics** [comment]
@AmeliaMN Good suggestion. Should be available now in the github version. I close this for now but happy to reopen if something is missing
