### ISSUE TITLE
Rectangularize `status`

### ISSUE THREAD

**Issue by chainsawriot** [schochastics/rtoot#9]
Need to think about how to rectangularize a single `status` #8 ; so that we can return an array of statuses (e.g. a timeline) as a tibble.

**Comment by chainsawriot** [comment]
Good artists copy

https://github.com/ropensci/rtweet/blob/2c4885be12af259ed7d3ffe9703416216ea994be/R/tweets_and_users.R

**Comment by chainsawriot** [comment]
https://github.com/ropensci/rtweet/blob/8552ccf3d10067665e2011d54d3ae2e830894e3a/R/tweet_object.R

**Comment by schochastics** [comment]
hmm was afraid we need to hardcode the response structure
